import React from 'react';
import { AlertCircle, CheckCircle2, User, Ban } from 'lucide-react';

interface AIRoleClarityBannerProps {
  contentType: 'ai-draft' | 'ai-edited' | 'human-authored';
  originalAuthor?: string;
  aiEditedBy?: string;
  lastHumanReviewer?: string;
  lastReviewDate?: string;
}

export function AIRoleClarityBanner({ 
  contentType,
  originalAuthor,
  aiEditedBy,
  lastHumanReviewer,
  lastReviewDate
}: AIRoleClarityBannerProps) {
  
  if (contentType === 'ai-draft') {
    return (
      <div className="p-4 bg-blue-50 border-2 border-blue-300 rounded-lg">
        <div className="flex items-start gap-3 mb-3">
          <div className="flex-shrink-0 w-8 h-8 rounded-full bg-blue-200 flex items-center justify-center">
            <AlertCircle className="w-4 h-4 text-blue-700" />
          </div>
          <div className="flex-1">
            <div className="text-sm font-medium text-blue-900 mb-1">
              AI-Generated Draft Content
            </div>
            <p className="text-xs text-blue-800 leading-relaxed mb-2">
              This content was automatically generated by AI based on project context, 
              upstream approved protocol elements, and regulatory requirements (ISO 14155:2020, EU MDR 2017/745).
            </p>
          </div>
        </div>

        {/* AI Limits - Critical for Inspection */}
        <div className="pl-11 space-y-1.5 mb-3">
          <div className="flex items-start gap-2">
            <Ban className="w-3.5 h-3.5 text-blue-600 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-blue-800">
              <strong>AI cannot approve</strong> this content for regulatory use
            </p>
          </div>
          <div className="flex items-start gap-2">
            <Ban className="w-3.5 h-3.5 text-blue-600 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-blue-800">
              <strong>AI cannot resolve</strong> issues or make clinical decisions
            </p>
          </div>
          <div className="flex items-start gap-2">
            <Ban className="w-3.5 h-3.5 text-blue-600 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-blue-800">
              <strong>AI cannot act</strong> as author of record
            </p>
          </div>
        </div>

        <div className="pl-11 pt-3 border-t border-blue-200">
          <p className="text-xs text-blue-700">
            <strong>Required action:</strong> Review carefully, edit as needed, and approve 
            only when content meets protocol standards. Your approval establishes human 
            responsibility for this content.
          </p>
        </div>
      </div>
    );
  }

  if (contentType === 'ai-edited') {
    return (
      <div className="p-4 bg-purple-50 border-2 border-purple-300 rounded-lg">
        <div className="flex items-start gap-3">
          <div className="flex-shrink-0 w-8 h-8 rounded-full bg-purple-200 flex items-center justify-center">
            <User className="w-4 h-4 text-purple-700" />
          </div>
          <div className="flex-1">
            <div className="text-sm font-medium text-purple-900 mb-1">
              Human-Edited Content (AI-Assisted)
            </div>
            <p className="text-xs text-purple-800 leading-relaxed mb-3">
              This content was originally AI-generated and has been reviewed and edited 
              by authorized personnel. AI provided drafting assistance only.
            </p>
            
            <div className="grid grid-cols-2 gap-3 text-xs pt-2 border-t border-purple-200">
              <div>
                <span className="text-purple-600">Original author:</span>
                <span className="ml-1.5 text-purple-900">AI System (draft)</span>
              </div>
              <div>
                <span className="text-purple-600">Edited by:</span>
                <span className="ml-1.5 text-purple-900">{aiEditedBy || 'Human reviewer'}</span>
              </div>
              {lastHumanReviewer && (
                <>
                  <div>
                    <span className="text-purple-600">Last reviewed by:</span>
                    <span className="ml-1.5 text-purple-900">{lastHumanReviewer}</span>
                  </div>
                  <div>
                    <span className="text-purple-600">Review date:</span>
                    <span className="ml-1.5 text-purple-900">{lastReviewDate}</span>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Human-authored content
  return (
    <div className="p-4 bg-green-50 border-2 border-green-300 rounded-lg">
      <div className="flex items-start gap-3">
        <div className="flex-shrink-0 w-8 h-8 rounded-full bg-green-200 flex items-center justify-center">
          <CheckCircle2 className="w-4 h-4 text-green-700" />
        </div>
        <div className="flex-1">
          <div className="text-sm font-medium text-green-900 mb-1">
            Human-Authored Content
          </div>
          <p className="text-xs text-green-800 leading-relaxed mb-2">
            This content was authored directly by qualified personnel without AI generation.
          </p>
          
          {originalAuthor && (
            <div className="text-xs pt-2 border-t border-green-200">
              <span className="text-green-600">Authored by:</span>
              <span className="ml-1.5 text-green-900">{originalAuthor}</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
